// HungarySportTickets (hungarysporttickets.com) — Sport events price comparison data
// All events have future 2026 dates. Every event has a unique image.
// v3 — dedup formatDate, cache bust
export type EventCategory =
  | "labdarugas"
  | "motorsport"
  | "tenisz"
  | "kosarlabda"
  | "kezilabda"
  | "egyeb";

export interface Supplier {
  id: string;
  name: string;
  countryCode: string;
  countryLabel: string;
  minPrice: number;
  maxPrice: number;
  currency: string;
  url: string;
  available: boolean;
  rating: number;
  reviewCount: number;
  isOfficial: boolean;
}

export interface Event {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  category: EventCategory;
  categoryLabel: string;
  date: string;
  time: string;
  venue: string;
  city: string;
  country: string;
  image: string;
  minPrice: number;
  maxPrice: number;
  currency: string;
  featured: boolean;
  description: string;
  tags: string[];
  suppliers: Supplier[];
}

export const CATEGORIES: { slug: EventCategory; label: string }[] = [
  { slug: "labdarugas", label: "Labdarúgás" },
  { slug: "motorsport", label: "Motorsport" },
  { slug: "tenisz", label: "Tenisz" },
  { slug: "kosarlabda", label: "Kosárlabda" },
  { slug: "kezilabda", label: "Kézilabda" },
  { slug: "egyeb", label: "Egyéb sport" },
];

export const EVENTS: Event[] = [
  // ─── LABDARÚGÁS ──────────────────────────────────────────────────────────
  {
    id: "1",
    slug: "ferencyaros-chelsea-europa-league",
    title: "Ferencváros TC vs. Chelsea FC",
    subtitle: "UEFA Európa Liga – Csoportkör",
    category: "labdarugas",
    categoryLabel: "Labdarúgás",
    date: "2026-05-14",
    time: "21:00",
    venue: "Groupama Aréna",
    city: "Budapest",
    country: "HU",
    image: "/images/football-match.jpg",
    minPrice: 22000,
    maxPrice: 185000,
    currency: "HUF",
    featured: true,
    description:
      "A Ferencváros TC hazai pályán fogadja a Chelsea FC-t az UEFA Európa Liga csoportkörében. A Groupama Aréna telt ház előtt rendezi meg az egyik legvárva várt európai mérkőzést.",
    tags: ["UEFA", "Európa Liga", "Ferencváros", "Chelsea", "Groupama Aréna"],
    suppliers: [
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 65000,
        maxPrice: 185000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
      {
        id: "stubhub",
        name: "StubHub",
        countryCode: "US",
        countryLabel: "USA",
        minPrice: 55000,
        maxPrice: 162000,
        currency: "HUF",
        url: "https://www.stubhub.com",
        available: true,
        rating: 4.1,
        reviewCount: 8700,
        isOfficial: false,
      },
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 22000,
        maxPrice: 145000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 28000,
        maxPrice: 138000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 32000,
        maxPrice: 125000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
    ],
  },
  {
    id: "4",
    slug: "ferencyaros-puskas-akademia-otp-liga",
    title: "Ferencváros TC vs. Puskás Akadémia FC",
    subtitle: "OTP Bank Liga – 25. forduló",
    category: "labdarugas",
    categoryLabel: "Labdarúgás",
    date: "2026-04-25",
    time: "18:00",
    venue: "Groupama Aréna",
    city: "Budapest",
    country: "HU",
    image: "/images/football-otp-liga.jpg",
    minPrice: 4500,
    maxPrice: 28000,
    currency: "HUF",
    featured: false,
    description:
      "Az OTP Bank Liga 25. fordulójában a Ferencváros TC otthon fogadja a Puskás Akadémia FC-t. A rangadónak számító mérkőzés a bajnokság élmezőnyét érinti.",
    tags: ["OTP Bank Liga", "Ferencváros", "Puskás Akadémia", "Labdarúgás", "Bajnokság"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 4500,
        maxPrice: 28000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 5000,
        maxPrice: 24000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 5500,
        maxPrice: 22000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
    ],
  },
  {
    id: "5",
    slug: "magyarorszag-nemetorszag-valogatott",
    title: "Magyarország vs. Németország",
    subtitle: "UEFA Nemzetek Ligája – A Liga",
    category: "labdarugas",
    categoryLabel: "Labdarúgás",
    date: "2026-06-06",
    time: "20:45",
    venue: "Puskás Aréna",
    city: "Budapest",
    country: "HU",
    image: "/images/football-national-team.jpg",
    minPrice: 12000,
    maxPrice: 78000,
    currency: "HUF",
    featured: true,
    description:
      "A magyar válogatott a Puskás Arénában fogadja a német labdarúgó-válogatottat az UEFA Nemzetek Ligájának A Ligájában. A telt ház előtt rendezendő mérkőzés kiemelkedő téttel bír.",
    tags: ["Válogatott", "Nemzetek Ligája", "Magyarország", "Németország", "Puskás Aréna"],
    suppliers: [
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 38000,
        maxPrice: 78000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 12000,
        maxPrice: 65000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 14000,
        maxPrice: 58000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
      {
        id: "stubhub",
        name: "StubHub",
        countryCode: "US",
        countryLabel: "USA",
        minPrice: 32000,
        maxPrice: 72000,
        currency: "HUF",
        url: "https://www.stubhub.com",
        available: true,
        rating: 4.1,
        reviewCount: 8700,
        isOfficial: false,
      },
    ],
  },
  // ─── MOTORSPORT ──────────────────────────────────────────────────────────
  {
    id: "2",
    slug: "formula1-magyar-nagydij",
    title: "Formula 1 Magyar Nagydíj 2026",
    subtitle: "Hungaroring – Versenynap",
    category: "motorsport",
    categoryLabel: "Motorsport",
    date: "2026-08-02",
    time: "15:00",
    venue: "Hungaroring",
    city: "Mogyoród",
    country: "HU",
    image: "/images/formula1-race.jpg",
    minPrice: 45000,
    maxPrice: 320000,
    currency: "HUF",
    featured: true,
    description:
      "A Formula 1 Magyar Nagydíja a Hungaroringen kerül megrendezésre. Az autóversenyzes legnagyobb eseménye Magyarországon, ahol a világ legjobb pilótái és csapatai mérkőznek meg egymással.",
    tags: ["F1", "Formula 1", "Hungaroring", "Magyar Nagydíj", "Motorsport"],
    suppliers: [
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 125000,
        maxPrice: 320000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
      {
        id: "stubhub",
        name: "StubHub",
        countryCode: "US",
        countryLabel: "USA",
        minPrice: 112000,
        maxPrice: 285000,
        currency: "HUF",
        url: "https://www.stubhub.com",
        available: true,
        rating: 4.1,
        reviewCount: 8700,
        isOfficial: false,
      },
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 45000,
        maxPrice: 245000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 52000,
        maxPrice: 258000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 55000,
        maxPrice: 240000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
    ],
  },
  {
    id: "7",
    slug: "motogp-red-bull-ring-ausztria",
    title: "MotoGP – Red Bull Ring",
    subtitle: "Ausztriai Nagydíj – Versenynap",
    category: "motorsport",
    categoryLabel: "Motorsport",
    date: "2026-07-12",
    time: "14:00",
    venue: "Red Bull Ring",
    city: "Spielberg",
    country: "AT",
    image: "/images/motorsport-rally.jpg",
    minPrice: 35000,
    maxPrice: 125000,
    currency: "HUF",
    featured: false,
    description:
      "A MotoGP Ausztriai Nagydíja a Red Bull Ringen kerül megrendezésre. A világ legjobb motorosai versenyeznek a festői hegyi pályán, alig 3 órányi autóútra Budapesttől.",
    tags: ["MotoGP", "Red Bull Ring", "Ausztria", "Motorsport", "Motor"],
    suppliers: [
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 58000,
        maxPrice: 125000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
      {
        id: "stubhub",
        name: "StubHub",
        countryCode: "US",
        countryLabel: "USA",
        minPrice: 52000,
        maxPrice: 115000,
        currency: "HUF",
        url: "https://www.stubhub.com",
        available: true,
        rating: 4.1,
        reviewCount: 8700,
        isOfficial: false,
      },
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 35000,
        maxPrice: 98000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: false,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 38000,
        maxPrice: 105000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
    ],
  },
  // ─── TENISZ ──────────────────────────────────────────────────────────────
  {
    id: "3",
    slug: "atp-budapest-open-tenisz",
    title: "Budapest Open ATP 250",
    subtitle: "Agyagpályás tenisztorna – Döntő",
    category: "tenisz",
    categoryLabel: "Tenisz",
    date: "2026-04-19",
    time: "14:00",
    venue: "Római Teniszakadémia",
    city: "Budapest",
    country: "HU",
    image: "/images/tennis-match.jpg",
    minPrice: 6500,
    maxPrice: 48000,
    currency: "HUF",
    featured: true,
    description:
      "A Budapest Open ATP 250 tornán a világ legjobb teniszezői mérik össze tudásukat a Római Teniszakadémia agyagpályáin. Az esemény tradicionálisan az európai agyagszezont nyitja meg.",
    tags: ["ATP", "Tenisz", "Budapest Open", "Agyag", "ATP 250"],
    suppliers: [
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 18000,
        maxPrice: 48000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 6500,
        maxPrice: 38000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 7500,
        maxPrice: 36000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 8000,
        maxPrice: 34000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
    ],
  },
  {
    id: "3b",
    slug: "wta-budapest-grand-prix-tenisz",
    title: "WTA Budapest Grand Prix",
    subtitle: "Agyagpályás tenisztorna – Elődöntők",
    category: "tenisz",
    categoryLabel: "Tenisz",
    date: "2026-07-05",
    time: "13:00",
    venue: "Római Teniszakadémia",
    city: "Budapest",
    country: "HU",
    image: "/images/tennis-tournament.jpg",
    minPrice: 5000,
    maxPrice: 35000,
    currency: "HUF",
    featured: false,
    description:
      "A WTA Budapest Grand Prix az agyagszezón egyik legszínesebb tornája. A világ top-50 teniszeznői versengenek a Római Teniszakadémia nézőkkel teli pályáin.",
    tags: ["WTA", "Tenisz", "Budapest Grand Prix", "Agyag", "Noi tenisz"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 5000,
        maxPrice: 35000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 5500,
        maxPrice: 30000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 6000,
        maxPrice: 28000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
    ],
  },
  // ─── KOSÁRLABDA ──────────────────────────────────────────────────────────
  {
    id: "6",
    slug: "fiba-kosarlabda-magyarorszag-franciaorszag",
    title: "Magyarország vs. Franciaország",
    subtitle: "FIBA Kosárlabda Eb-selejtező",
    category: "kosarlabda",
    categoryLabel: "Kosárlabda",
    date: "2026-11-14",
    time: "19:30",
    venue: "MVM Dome",
    city: "Budapest",
    country: "HU",
    image: "/images/basketball-match.jpg",
    minPrice: 4500,
    maxPrice: 28000,
    currency: "HUF",
    featured: false,
    description:
      "A magyar kosárlabda-válogatott az MVM Dome-ban fogadja a francia csapatot a FIBA Európa-bajnoki selejtező keretében. A mérkőzés hatalmas téttel bír a csoportban.",
    tags: ["FIBA", "Kosárlabda", "Válogatott", "MVM Dome", "Franciaország"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 4500,
        maxPrice: 28000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 5000,
        maxPrice: 24000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 5500,
        maxPrice: 22000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
    ],
  },
  {
    id: "6b",
    slug: "alba-berlin-falco-kosarlabda-euroliga",
    title: "Falco KC vs. Alba Berlin",
    subtitle: "EuroLeague Kosárlabda – D csoport",
    category: "kosarlabda",
    categoryLabel: "Kosárlabda",
    date: "2026-10-17",
    time: "18:00",
    venue: "Savaria Aréna",
    city: "Szombathely",
    country: "HU",
    image: "/images/basketball-euroliga.jpg",
    minPrice: 3500,
    maxPrice: 18000,
    currency: "HUF",
    featured: false,
    description:
      "A Falco KC a Savaria Arénában fogadja az Alba Berlint az EuroLeague csoportkörének mérkőzésén. A szombathelyi csapat legjobb nemzetközi szereplésének számít ez a torna.",
    tags: ["EuroLeague", "Kosárlabda", "Falco KC", "Alba Berlin", "Szombathely"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 3500,
        maxPrice: 18000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 4000,
        maxPrice: 15000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 6000,
        maxPrice: 18000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
    ],
  },
  // ─── KÉZILABDA ───────────────────────────────────────────────────────────
  {
    id: "8",
    slug: "fradi-debrecen-kezilabda-kupa",
    title: "Ferencváros vs. DVSC Schaeffler",
    subtitle: "Magyar Kézilabda Kupa – Döntő",
    category: "kezilabda",
    categoryLabel: "Kézilabda",
    date: "2026-05-23",
    time: "17:30",
    venue: "BOK Hall",
    city: "Budapest",
    country: "HU",
    image: "/images/handball-match.jpg",
    minPrice: 2500,
    maxPrice: 14000,
    currency: "HUF",
    featured: false,
    description:
      "A Magyar Kézilabda Kupa döntőjét a BOK Hallban rendezik meg, ahol a Ferencváros a debreceni DVSC Schaefflerrel csap össze a legrangosabb hazai kupaért.",
    tags: ["Kézilabda", "Magyar Kupa", "Ferencváros", "DVSC", "BOK Hall"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 2500,
        maxPrice: 14000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 3000,
        maxPrice: 12000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
    ],
  },
  {
    id: "8b",
    slug: "pick-szeged-barcelona-kezilabda-bl",
    title: "Pick Szeged vs. FC Barcelona",
    subtitle: "Kézilabda Bajnokok Ligája – Csoportkör",
    category: "kezilabda",
    categoryLabel: "Kézilabda",
    date: "2026-04-09",
    time: "19:00",
    venue: "Pick Aréna",
    city: "Szeged",
    country: "HU",
    image: "/images/handball-champions-league.jpg",
    minPrice: 4000,
    maxPrice: 22000,
    currency: "HUF",
    featured: true,
    description:
      "A Pick Szeged hazai pályán fogadja az FC Barcelonát a Kézilabda Bajnokok Ligájának csoportkörében. A telt házas Pick Aréna az egyik legmeghatározóbb hazai kézilabda-mérkőzés.",
    tags: ["Kézilabda", "Bajnokok Ligája", "Pick Szeged", "FC Barcelona", "Szeged"],
    suppliers: [
      {
        id: "viagogo",
        name: "Viagogo",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 10000,
        maxPrice: 22000,
        currency: "HUF",
        url: "https://www.viagogo.com",
        available: true,
        rating: 3.8,
        reviewCount: 12400,
        isOfficial: false,
      },
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 4000,
        maxPrice: 18000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 4500,
        maxPrice: 16000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
      {
        id: "stubhub",
        name: "StubHub",
        countryCode: "US",
        countryLabel: "USA",
        minPrice: 8000,
        maxPrice: 20000,
        currency: "HUF",
        url: "https://www.stubhub.com",
        available: true,
        rating: 4.1,
        reviewCount: 8700,
        isOfficial: false,
      },
    ],
  },
  // ─── EGYÉB SPORT ─────────────────────────────────────────────────────────
  {
    id: "9",
    slug: "atletika-budapest-maraton",
    title: "Budapest Marathon Festival",
    subtitle: "Athletikai esemény – Maraton + Félmaraton",
    category: "egyeb",
    categoryLabel: "Egyéb sport",
    date: "2026-10-11",
    time: "09:00",
    venue: "Hősök tere",
    city: "Budapest",
    country: "HU",
    image: "/images/athletics-event.jpg",
    minPrice: 8000,
    maxPrice: 45000,
    currency: "HUF",
    featured: false,
    description:
      "A Budapest Marathon Festival Közép-Európa egyik leglátványosabb utcai futóeseménye. A rajtpont a Hősök terén van, a nyomvonal Budapest legszebb látványosságain vezet keresztül.",
    tags: ["Maraton", "Atletika", "Budapest", "Futás", "Hősök tere"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 8000,
        maxPrice: 45000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 9000,
        maxPrice: 40000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
      {
        id: "eventim",
        name: "Eventim",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 10000,
        maxPrice: 38000,
        currency: "HUF",
        url: "https://www.eventim.hu",
        available: true,
        rating: 4.2,
        reviewCount: 9500,
        isOfficial: false,
      },
    ],
  },
  {
    id: "9b",
    slug: "atletika-eb-selejtezok-budapest",
    title: "Atlétika Eb-selejtező Gála",
    subtitle: "Atlétikai Gála – Fedett pályás verseny",
    category: "egyeb",
    categoryLabel: "Egyéb sport",
    date: "2026-12-05",
    time: "18:00",
    venue: "Papp László Budapest Sportaréna",
    city: "Budapest",
    country: "HU",
    image: "/images/athletics-indoor.jpg",
    minPrice: 3500,
    maxPrice: 20000,
    currency: "HUF",
    featured: false,
    description:
      "A fedett pályás atlétikai gálán a legjobb magyar és külföldi atléták mérik össze tudásukat a Papp László Sportarénában. Futás, ugrás és dobószámok a legjobb atlétáktól.",
    tags: ["Atlétika", "Gála", "Fedett pálya", "Sportaréna", "Budapest"],
    suppliers: [
      {
        id: "ticketmaster",
        name: "Jegy.hu",
        countryCode: "EU",
        countryLabel: "EU",
        minPrice: 3500,
        maxPrice: 20000,
        currency: "HUF",
        url: "https://www.jegy.hu",
        available: true,
        rating: 4.3,
        reviewCount: 21000,
        isOfficial: true,
      },
      {
        id: "liveticket",
        name: "Jegymester.hu",
        countryCode: "HU",
        countryLabel: "HU",
        minPrice: 4000,
        maxPrice: 16000,
        currency: "HUF",
        url: "https://www.jegymester.hu",
        available: true,
        rating: 4.0,
        reviewCount: 3200,
        isOfficial: false,
      },
    ],
  },
];

export function getEventBySlug(slug: string): Event | undefined {
  return EVENTS.find((e) => e.slug === slug);
}

export function getEventsByCategory(category: EventCategory): Event[] {
  return EVENTS.filter((e) => e.category === category);
}

export function getFeaturedEvents(): Event[] {
  return EVENTS.filter((e) => e.featured);
}

export function formatPrice(price: number, currency = "HUF"): string {
  return new Intl.NumberFormat("hu-HU", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr + "T00:00:00");
  return new Intl.DateTimeFormat("hu-HU", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
}

export const SUPPLIERS_INFO: {
  id: string;
  name: string;
  countryCode: string;
  countryLabel: string;
  url: string;
  description: string;
  isOfficial: boolean;
}[] = [
  {
    id: "ticketmaster",
    name: "Jegy.hu",
    countryCode: "HU",
    countryLabel: "Magyarország",
    url: "https://www.jegy.hu",
    description:
      "Magyarország egyik vezető online jegyértékesítő platformja. Széles kínálattal rendelkezik sport-, zenei és kulturális eseményekre.",
    isOfficial: true,
  },
  {
    id: "viagogo",
    name: "Viagogo",
    countryCode: "EU",
    countryLabel: "EU / Globális",
    url: "https://www.viagogo.com",
    description:
      "Globális másodlagos jegypiac, ahol magánszemélyek és viszonteladók kínálnak jegyeket sporteseményekre és koncertekre szerte a világon.",
    isOfficial: false,
  },
  {
    id: "eventim",
    name: "Eventim",
    countryCode: "EU",
    countryLabel: "EU",
    url: "https://www.eventim.hu",
    description:
      "Európa egyik vezető jegyértékesítő hálózata, erős magyarországi jelenléttel. Számos sport- és kulturális esemény jegyei elérhetők.",
    isOfficial: true,
  },
  {
    id: "liveticket",
    name: "Jegymester.hu",
    countryCode: "HU",
    countryLabel: "Magyarország",
    url: "https://www.jegymester.hu",
    description:
      "Magyar jegyértékesítő platform sport- és kulturális eseményekre, széles hazai kínálattal.",
    isOfficial: false,
  },
  {
    id: "stubhub",
    name: "StubHub",
    countryCode: "US",
    countryLabel: "USA / Globális",
    url: "https://www.stubhub.com",
    description:
      "Az USA-ban alapított, mára globálisan ismert másodlagos jegypiac. Európai sporteseményekre is széles kínálattal rendelkezik.",
    isOfficial: false,
  },
];


